"""
cascade/agents/coder.py
────────────────────────
Coder Agent — Patch Generator (Node 3 of the DevOps pipeline).

Converts a selected Tree-of-Thoughts branch into a concrete, applicable
unified diff patch (git diff format). The patch is:
  1. Generated by LLM against actual file contents from the repository
  2. Validated locally (git apply --check) before being stored
  3. Re-generated with test failures as feedback (in the retry loop)

The Cascade Retry Loop:
  When the Sandbox Tester (Phase 3) fails:
  → test_results.xml is fed back as new inputs to THIS agent
  → The Coder re-generates the patch with failure context
  → The entire step re-runs (new input_hash) with test info included
  → Cache correctly captures the "fixed" version without re-running Explorer/Planner

Output artifacts:
  patch.diff        — Unified diff (git apply format)
  cost_manifest.json — Per-call LLM cost breakdown
"""

from __future__ import annotations

import re
import subprocess
import tempfile
import shutil
import asyncio
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

from cascade.agents.base import BaseAgent
from cascade.agents.tools import WorkspaceTools


# ── Data Models ───────────────────────────────────────────────────────────────

class FileChange(BaseModel):
    """A single file change within the patch."""
    path: str
    action: str = Field(description="modify / create / delete")
    diff: str = Field(description="Unified diff for this file")


class PatchOutput(BaseModel):
    """LLM-generated patch output."""
    explanation: str = Field(
        description="1-paragraph explanation of what the patch does and why"
    )
    changes: list[FileChange] = Field(
        description="List of file changes to apply"
    )
    test_strategy: str = Field(
        description="How to test this patch (which tests to run, what to check)"
    )
    breaking_changes: list[str] = Field(
        default_factory=list,
        description="Any breaking changes (API, config, behavior)"
    )


class ReActAction(BaseModel):
    """Action output from the ReAct coder model."""
    thought: str = Field(description="Step-by-step reasoning about what to do next.")
    tool_name: str = Field(description="The tool to call: read_file, write_file, edit_file, grep_search, list_dir, finish")
    tool_input: dict[str, Any] = Field(default_factory=dict, description="Arguments for the tool (e.g. {'path': 'main.py'} or {'query': 'def add'}). For 'finish', pass empty dict.")
    explanation: str = Field(default="", description="1-paragraph explanation of what the final patch does (only when tool_name is 'finish').")
    test_strategy: str = Field(default="", description="How to test this patch (only when tool_name is 'finish').")


# ── Coder Agent ───────────────────────────────────────────────────────────────

class CoderAgent(BaseAgent):
    """
    Generates a git-compatible unified diff patch from a solution branch.

    On first run: generates patch from branch plan + file contents.
    On retry (with test_results): regenerates with failure context.
    """

    agent_name = "coder"

    async def execute(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """
        Full coder pipeline:
        1. Load selected branch from Planner
        2. Read relevant file contents from repo
        3. Generate unified diff patch via LLM
        4. Validate patch is syntactically correct
        5. Store patch.diff in CAS

        Inputs (from Planner outputs + optional Tester feedback):
            planner.selected_branch:    Dict of the selected ToT branch
            planner.tot_branches_uri:   CAS URI to full ToT branches
            planner.analysis_summary:   Root cause summary
            issue_title:                GitHub issue title
            issue_body:                 GitHub issue description
            repo_url:                   For context in patch headers
            commit_sha:                 Base commit SHA for the diff

            [On retry — from Tester:]
            test_results_xml:           Full test output XML (as string)
            test_error_summary:         Human-readable test failure summary
            previous_patch_uri:         CAS URI of the failed patch (for context)
            retry_count:                Current retry attempt number

        Returns:
            patch_uri:              CAS URI → patch.diff (full unified diff)
            patch_diff:             Inline diff (for small patches, convenience)
            files_changed:          List of file paths changed
            validation_passed:      Whether git apply --check passed locally
        """
        selected_branch = inputs.get("planner.selected_branch", {})
        analysis_summary = inputs.get("planner.analysis_summary", "")
        issue_title = inputs.get("issue_title", "")
        issue_body = inputs.get("issue_body", "")
        repo_url = inputs.get("repo_url", "")
        commit_sha = inputs.get("commit_sha", inputs.get("explorer.commit_sha", "HEAD"))

        # Retry-specific inputs (from Tester feedback)
        test_results_xml = inputs.get("test_results_xml", "")
        test_error_summary = inputs.get("test_error_summary", "")
        previous_patch_uri = inputs.get("previous_patch_uri", "")
        retry_count = inputs.get("retry_count", 0)

        # Load previous patch for context on retry
        previous_patch = ""
        if previous_patch_uri and self._artifact_store and retry_count > 0:
            try:
                previous_patch = self._artifact_store.get_text(previous_patch_uri)
            except KeyError:
                pass

        # ── Generate the patch ────────────────────────────────────────────────
        patch_res = await self._generate_patch(
            branch=selected_branch,
            analysis_summary=analysis_summary,
            issue_title=issue_title,
            issue_body=issue_body,
            repo_url=repo_url,
            commit_sha=commit_sha,
            test_results_xml=test_results_xml,
            test_error_summary=test_error_summary,
            previous_patch=previous_patch,
            retry_count=retry_count,
        )

        if isinstance(patch_res, tuple):
            full_diff, files_changed, explanation, test_strategy = patch_res
            breaking_changes = []
        else:
            # Legacy/Mock test support returning PatchOutput
            patch_output = patch_res
            full_diff = self._assemble_diff(patch_output, commit_sha)
            files_changed = [c.path for c in patch_output.changes]
            explanation = patch_output.explanation
            test_strategy = patch_output.test_strategy
            breaking_changes = getattr(patch_output, "breaking_changes", [])

        # ── Validate patch locally ────────────────────────────────────────────
        validation_passed, validation_error = self._validate_patch_syntax(full_diff)

        # ── Store artifacts ───────────────────────────────────────────────────
        patch_uri = self._artifact_store.put_text(full_diff) if self._artifact_store else ""
        cost_manifest_uri = self.store_cost_manifest()

        return {
            "patch_uri": patch_uri,
            "patch_diff": full_diff[:2000],  # Inline preview for small patches
            "files_changed": files_changed,
            "validation_passed": validation_passed,
            "validation_error": validation_error or "",
            "patch_explanation": explanation,
            "test_strategy": test_strategy,
            "breaking_changes": breaking_changes,
            "retry_count": retry_count,
            "cost_manifest_uri": cost_manifest_uri,
            **self.get_cost_outputs(),
        }

    # ── Patch Generation ──────────────────────────────────────────────────────

    async def _generate_patch(
        self,
        branch: dict[str, Any],
        analysis_summary: str,
        issue_title: str,
        issue_body: str,
        repo_url: str,
        commit_sha: str,
        test_results_xml: str,
        test_error_summary: str,
        previous_patch: str,
        retry_count: int,
    ) -> tuple[str, list[str], str, str] | PatchOutput:
        """Generate a unified diff using LLM ReAct loop or return mock in mock mode."""
        import os
        if self._is_mock_mode():
            diff_content = (
                "diff --git a/app.py b/app.py\n"
                "--- a/app.py\n"
                "+++ b/app.py\n"
                "@@ -10,3 +10,8 @@\n"
                " app = FastAPI()\n"
                "+\n"
                "+# Conditional docs disabling for production\n"
                "+if os.environ.get('ENV') == 'production':\n"
                "+    app.docs_url = None\n"
                "+    app.redoc_url = None\n"
            )
            return diff_content, ["app.py"], "Conditionally configure docs_url and redoc_url on FastAPI instantiation based on ENV.", "Run pytest tests/test_docs.py"

        tmp_dir = tempfile.mkdtemp(prefix="cascade_coder_")
        repo_path = Path(tmp_dir) / "repo"
        repo_path.mkdir()

        try:
            # 1. Clone repository
            await self._clone_repo(repo_url, commit_sha, str(repo_path))

            # Apply previous patch if we are in a retry loop
            if previous_patch.strip():
                try:
                    self._apply_patch(str(repo_path), previous_patch)
                except Exception:
                    pass

            # 2. Instantiate tools
            tools = WorkspaceTools(repo_path)

            # 3. Setup prompt contexts
            retry_context = ""
            if retry_count > 0 and (test_error_summary or test_results_xml):
                retry_context = (
                    f"\n\n## RETRY #{retry_count} — Previous patch FAILED tests\n"
                    f"Test failure summary:\n{test_error_summary}\n\n"
                    f"Previous patch:\n"
                    f"```diff\n{previous_patch[:3000]}\n```\n"
                    f"Fix the issues identified in the test failures."
                )

            branch_plan = self._format_branch_plan(branch)
            impl_steps = self._format_implementation_steps(branch)

            system_prompt = (
                "You are an expert software engineer generating a patch to resolve a GitHub issue.\n"
                "You are in a ReAct loop. In each step, you must output a thought and choose a tool to run.\n"
                "Tools available:\n"
                "- read_file: {'path': relative_path}\n"
                "- write_file: {'path': relative_path, 'content': full_content}\n"
                "- edit_file: {'path': relative_path, 'target': exact_text_to_replace, 'replacement': new_text}\n"
                "- grep_search: {'query': search_string}\n"
                "- list_dir: {'path': relative_path}\n"
                "- finish: {}\n\n"
                "Once you are confident you have implemented the correct fix, call the 'finish' tool. "
                "Adhere to project style, import only existing items, and keep changes minimal."
            )

            user_prompt = (
                f"Repository: {repo_url} @ {commit_sha[:8]}\n\n"
                f"Issue: {issue_title}\n"
                f"Description: {issue_body[:1500]}\n\n"
                f"Root Cause Analysis:\n{analysis_summary}\n\n"
                f"Solution Approach:\n{branch_plan}\n\n"
                f"Implementation Steps:\n{impl_steps}"
                f"{retry_context}"
            )

            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ]

            files_changed = set()
            explanation = "No explanation provided."
            test_strategy = "No test strategy provided."
            max_steps = 12

            for step_idx in range(max_steps):
                history_str = "\n".join([f"{m['role'].upper()}: {m['content']}" for m in messages])
                user_msg = f"{history_str}\n\n[Step {step_idx + 1}/{max_steps}] Select your next Action."
                
                action = await self.llm_structured(
                    system=system_prompt,
                    user=user_msg,
                    output_model=ReActAction,
                )

                action_desc = f"Thought: {action.thought}\nAction: Call '{action.tool_name}' with args {action.tool_input}"
                messages.append({"role": "assistant", "content": action_desc})

                if action.tool_name == "finish":
                    explanation = action.explanation or explanation
                    test_strategy = action.test_strategy or test_strategy
                    break

                if action.tool_name in ("write_file", "edit_file") and "path" in action.tool_input:
                    files_changed.add(action.tool_input["path"])

                tool_output = tools.execute_tool(action.tool_name, action.tool_input)
                messages.append({"role": "user", "content": f"Tool output: {tool_output}"})

            # 4. Generate the git diff patch
            await self._run_git(["add", "-A"], cwd=str(repo_path))
            diff_text = await self._run_git(["diff", "--cached"], cwd=str(repo_path))

            return diff_text, list(files_changed), explanation, test_strategy

        finally:
            shutil.rmtree(tmp_dir, ignore_errors=True)

    async def _run_git(self, args: list[str], cwd: str) -> str:
        proc = await asyncio.create_subprocess_exec(
            "git", *args,
            cwd=cwd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()
        if proc.returncode != 0:
            raise RuntimeError(f"Git command failed: git {' '.join(args)}\nStderr: {stderr.decode()}")
        return stdout.decode().strip()

    async def _clone_repo(self, repo_url: str, commit_sha: str, dest_path: str) -> None:
        clone_args = ["clone"]
        if not _is_local_repo_url(repo_url):
            clone_args.extend(["--depth", "50", "--no-single-branch"])
        clone_args.extend([repo_url, dest_path])

        proc = await asyncio.create_subprocess_exec(
            "git", *clone_args,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        if proc.returncode != 0:
            raise RuntimeError(f"Git clone failed for {repo_url}: {stderr.decode().strip()}")

        if commit_sha and commit_sha != "HEAD":
            await self._checkout_commit(dest_path, commit_sha)

    async def _checkout_commit(self, repo_path: str, commit_sha: str) -> None:
        proc = await asyncio.create_subprocess_exec(
            "git", "-C", repo_path, "checkout", commit_sha,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        if proc.returncode == 0:
            return

        fetch = await asyncio.create_subprocess_exec(
            "git", "-C", repo_path, "fetch", "--depth", "1", "origin", commit_sha,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, fetch_stderr = await fetch.communicate()
        if fetch.returncode != 0:
            raise RuntimeError(
                "Git checkout failed and fetch fallback failed for "
                f"{commit_sha}: {stderr.decode().strip()} {fetch_stderr.decode().strip()}"
            )

        retry = await asyncio.create_subprocess_exec(
            "git", "-C", repo_path, "checkout", commit_sha,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, retry_stderr = await retry.communicate()
        if retry.returncode != 0:
            raise RuntimeError(
                f"Git checkout failed for {commit_sha}: {retry_stderr.decode().strip()}"
            )

    def _apply_patch(self, repo_path: str, patch_diff: str) -> None:
        patch_file = Path(repo_path) / "cascade.patch"
        patch_file.write_text(patch_diff, encoding="utf-8")

        result = subprocess.run(
            ["git", "apply", "--ignore-whitespace", "cascade.patch"],
            cwd=repo_path,
            capture_output=True,
            text=True,
        )
        if patch_file.exists():
            patch_file.unlink()

        if result.returncode != 0:
            raise RuntimeError(f"Failed to apply patch: {result.stderr}")

    def _format_branch_plan(self, branch: dict[str, Any]) -> str:
        """Format the selected branch for LLM context."""
        if not branch:
            return "  No branch plan available"
        lines = [
            f"Approach: {branch.get('approach_name', 'Unknown')}",
            f"Hypothesis: {branch.get('hypothesis', '')}",
            f"Reasoning: {branch.get('reasoning', '')}",
            f"Files to modify: {', '.join(branch.get('files_to_modify', []))}",
            f"Files to create: {', '.join(branch.get('files_to_create', []))}",
        ]
        return "\n".join(lines)

    def _format_implementation_steps(self, branch: dict[str, Any]) -> str:
        """Format implementation steps for LLM context."""
        steps = branch.get("implementation_steps", [])
        if not steps:
            return "  (no detailed steps — use reasoning to determine approach)"
        lines = []
        for step in steps:
            n = step.get("step_number", "?")
            desc = step.get("description", "")
            code_hint = step.get("code_hint", "")
            lines.append(f"  {n}. {desc}")
            if code_hint:
                lines.append(f"     Hint: {code_hint}")
        return "\n".join(lines)

    def _assemble_diff(self, patch_output: PatchOutput, commit_sha: str) -> str:
        """Assemble individual file diffs into a single unified patch."""
        if not patch_output.changes:
            return ""

        header = (
            f"# Cascade Auto-Generated Patch\n"
            f"# Base commit: {commit_sha}\n"
            f"# Explanation: {patch_output.explanation[:300]}\n\n"
        )
        diff_sections = []
        for change in patch_output.changes:
            diff = change.diff.strip()
            if diff and not diff.startswith("diff --git"):
                # Add header if LLM omitted it
                diff = f"diff --git a/{change.path} b/{change.path}\n{diff}"
            diff_sections.append(diff)

        return header + "\n\n".join(diff_sections)

    def _validate_patch_syntax(self, diff_text: str) -> tuple[bool, str | None]:
        """
        Validate that the patch is syntactically correct using git apply --check.

        Falls back to regex-based validation if git is not available.
        """
        if not diff_text.strip():
            return False, "Empty patch"

        # Try git apply --check in a temp directory
        try:
            with tempfile.TemporaryDirectory() as tmp:
                tmp_path = Path(tmp)

                # Initialize a minimal git repo for checking
                subprocess.run(
                    ["git", "init", str(tmp_path)],
                    capture_output=True, timeout=10
                )
                subprocess.run(
                    ["git", "config", "user.email", "cascade@cascade.dev"],
                    capture_output=True, cwd=str(tmp_path), timeout=5
                )
                subprocess.run(
                    ["git", "config", "user.name", "Cascade"],
                    capture_output=True, cwd=str(tmp_path), timeout=5
                )

                patch_file = tmp_path / "cascade.patch"
                patch_file.write_text(diff_text, encoding="utf-8")

                result = subprocess.run(
                    ["git", "apply", "--check", "--ignore-whitespace", str(patch_file)],
                    capture_output=True,
                    cwd=str(tmp_path),
                    timeout=15,
                    text=True,
                )

                if result.returncode == 0:
                    return True, None
                else:
                    return False, result.stderr.strip()[:300]

        except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
            # git not available — fall back to syntax check
            return self._validate_patch_syntax_regex(diff_text)

    def _validate_patch_syntax_regex(self, diff_text: str) -> tuple[bool, str | None]:
        """Regex-based patch syntax validation (fallback when git unavailable)."""
        has_hunk_header = bool(re.search(r"^@@.*@@", diff_text, re.MULTILINE))
        has_file_header = bool(re.search(r"^(?:---|\+\+\+|diff --git)", diff_text, re.MULTILINE))

        if not has_file_header:
            return False, "Missing file headers (--- / +++ or diff --git)"
        if not has_hunk_header:
            return False, "Missing hunk headers (@@ ... @@)"
        return True, None


def _is_local_repo_url(repo_url: str) -> bool:
    """Return True when repo_url points to a local path rather than a remote."""
    return bool(re.match(r"^[A-Za-z]:[\\/]", repo_url)) or Path(repo_url).expanduser().exists()
